module.exports = {
    duplicateEmail: 'Email already exists.',
    createdSuccess: 'User created successfully.',
    loginSuccess: 'Login successful.',
    otpSent: 'OTP has been sent to your email.',
    otpVerified: 'OTP verified successfully.',
    recordsNotFound: 'No records found.',
    recordsUpdated: 'Records updated successfully.',
    registrationError:'Registering  User Error',
    loginUserError:'logging User error',
    invaildCredentials:'Invinvaild User',
    otpRequesterror:'Otp Request Error',
    userNotFound:'User Not Found',
    otpInvalidOrExpired:'Otp expired',
    logHealthMetric :'Error logging health metric',
    metricLogged:'Metric logged sucess',
    otpVerificationError:'Otp Verification Error',
    fetchHealthLogs: "Error fetching health logs.",
    healthLogFetched: "Health log fetched successfully.",
    healthLogsFetched: "Health logs fetched successfully.",
    healthLogNotFound: "Health log not found.",
    updateHealthLog: "Error updating health log.",
    healthLogUpdated: "Health log updated successfully.",
    deleteHealthLog: "Error deleting health log.",
    healthLogDeleted: "Health log deleted successfully.",
    fetchHealthLogsId:"Fetching error log by Id",
    healthLogFetchedId:"Health log fetched successfully by Id",
};
